<a href="https://colab.research.google.com/github/Stephen-sanchez1/datasci_2_manipulation/blob/main/Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load Packages

In [1]:
import pandas as pd
import numpy as np
import re
import polars as pl
import time

## Load Data

* Original Uncleaned Data

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Stephen-sanchez1/datasci_2_manipulation/main/datasets/healthcare_data_cleaning.csv')
df

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
1,25,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59,missing,174,58,430.68365678679174,195,missing,4,80.78647284463952
2,51,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79,119,161,56,315.0709305262176,missing,37,2,64.3921393009105
3,18,Female,Taylorfort,Pennsylvania,Yes,missing,Cash,Dr. Williams,Flu,Med_A,General,99,115,171,52,320.2998987723972,175,108,2,8.872859215315316
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,74,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65,112,169,61,309.16444606680665,183,10,3,63.20478776719894
104996,37,Male,Mckeetown,Utah,Yes,No,Cash,Dr. Jones,Covid-19,Med_C,General,missing,111,165,67,missing,191,47,2,113.86764025370326
104997,51,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89,118,179,71,320.8304180033907,172,39,3,35.622420232475356
104998,missing,Female,Heidiborough,missing,Yes,No,Cash,Dr. Smith,Covid-19,Med_A,Follow-Up,74,123,167,75,5.341231420036174,180,79,missing,124.4083409893742
104999,45,Female,South Jeffrey,Massachusetts,No,Yes,Cash,Dr. Brown,Allergy,Med_D,General,77,140,167,62,454.94983945860804,167,81,missing,87.91060149353706

## Data Cleaning with Pandas:
* Identify and handle missing values in the dataset.
*Remove any duplicate rows and columns, if they exist.
*Clean column names

In [3]:
# Replace 'missing' strings with  NaN, that way it shows up as a missing value.
df.replace('missing', np.nan, inplace=True)

In [4]:
# Check for missing values in each column
print(df.isnull().sum())

Patient Age              5249
Gender                   5261
City of Residence        5227
State of Residence       5248
Has Insurance            5246
Visited Last Month       5245
Payment Method           5202
Preferred Doctor         5247
Disease Diagnosed        5271
Medication Prescribed    5262
Type of Appointment      5250
Average Heart Rate       5278
Average BP               5255
Height (in cm)           5244
Weight (in kg)           5264
Payment Due ($)          5229
Last Visit (days ago)    5259
Visit Duration (mins)    5276
Number of Tests          5272
Prescription Cost ($)    5216
dtype: int64

In [5]:
# Drop rows with any missing values
df.dropna(inplace=True)
df

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
7,52,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99,129,170,47,387.08504353508863,179,108,2,76.96592632951703
8,20,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67,108,173,86,172.5483427968999,174,91,2,142.31710767890775
11,40,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65,106,166,82,299.1426761400895,193,92,1,77.71536034261702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76,93,178,66,462.56567087397013,189,55,3,59.74631825267156
104993,42,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80,129,171,78,131.35632576282202,185,22,6,104.43016736588544
104994,53,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68,109,172,75,488.0316041186948,167,25,5,69.54228578689846
104995,74,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65,112,169,61,309.16444606680665,183,10,3,63.20478776719894
104997,51,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89,118,179,71,320.8304180033907,172,39,3,35.622420232475356

In [6]:
# Removing duplicate rows
print(df.drop_duplicates(inplace=True))

None

# Cleaning Column Names

In [7]:
def clean_column_name(column_name):
    column_name = column_name.lower()  # Convert to lowercase
    column_name = column_name.replace(" ", "_")  # Replace spaces with underscores
    column_name = column_name.replace("(", "")  # Remove opening parenthesis
    column_name = column_name.replace(")", "")  # Remove closing parenthesis
    column_name = column_name.replace("$", "usd")  # Replace dollar sign with "usd"
    column_name = '_'.join(column_name.split('_'))  # Remove consecutive underscores
    return column_name

# List of your original column names
column_names = [
    "Patient Age", "Gender", "City of Residence", "State of Residence",
    "Has Insurance", "Visited Last Month", "Payment Method",
    "Preferred Doctor", "Disease Diagnosed", "Medication Prescribed",
    "Type of Appointment", "Average Heart Rate", "Average BP",
    "Height (in cm)", "Weight (in kg)", "Payment Due ($)",
    "Last Visit (days ago)", "Visit Duration (mins)",
    "Number of Tests", "Prescription Cost ($)"
]


# Applying the function to clean column names and assign them back to the dataframe
df.columns = [clean_column_name(col) for col in df.columns]

# Print new dataset

df

,patient_age,gender,city_of_residence,state_of_residence,has_insurance,visited_last_month,payment_method,preferred_doctor,disease_diagnosed,medication_prescribed,type_of_appointment,average_heart_rate,average_bp,height_in_cm,weight_in_kg,payment_due_usd,last_visit_days_ago,visit_duration_mins,number_of_tests,prescription_cost_usd
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
7,52,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99,129,170,47,387.08504353508863,179,108,2,76.96592632951703
8,20,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67,108,173,86,172.5483427968999,174,91,2,142.31710767890775
11,40,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65,106,166,82,299.1426761400895,193,92,1,77.71536034261702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76,93,178,66,462.56567087397013,189,55,3,59.74631825267156
104993,42,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80,129,171,78,131.35632576282202,185,22,6,104.43016736588544
104994,53,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68,109,172,75,488.0316041186948,167,25,5,69.54228578689846
104995,74,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65,112,169,61,309.16444606680665,183,10,3,63.20478776719894
104997,51,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89,118,179,71,320.8304180033907,172,39,3,35.622420232475356

## Data Transformation:
* Create new columns based on existing ones (e.g., if you have a 'birth_date' column, create an 'age' column).
* Aggregate data using groupby and compute summary statistics.
* Use pivot tables or cross-tabulations for multi-dimensional analysis.

# Creating New Column

In [8]:
#Creating new column

#  'total_due_usd' to represent the total amount due by a patient
# 'payment_due_usd': the amount due for services/consultation
# 'prescription_cost_usd': the cost of prescribed medications

#  The column is the sum of 'payment_due_usd' and 'prescription_cost_usd'
df['total_due_usd'] = df['payment_due_usd'] + df['prescription_cost_usd']

df

,patient_age,gender,city_of_residence,state_of_residence,has_insurance,visited_last_month,payment_method,preferred_doctor,disease_diagnosed,medication_prescribed,...,average_heart_rate,average_bp,height_in_cm,weight_in_kg,payment_due_usd,last_visit_days_ago,visit_duration_mins,number_of_tests,prescription_cost_usd,total_due_usd
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889,65.4572157812622415.71751735532889
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,...,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532,264.214737247331977.48311304645532
7,52,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,99,129,170,47,387.08504353508863,179,108,2,76.96592632951703,387.0850435350886376.96592632951703
8,20,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,...,67,108,173,86,172.5483427968999,174,91,2,142.31710767890775,172.5483427968999142.31710767890775
11,40,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,...,65,106,166,82,299.1426761400895,193,92,1,77.71536034261702,299.142676140089577.71536034261702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,...,76,93,178,66,462.56567087397013,189,55,3,59.74631825267156,462.5656708739701359.74631825267156
104993,42,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,...,80,129,171,78,131.35632576282202,185,22,6,104.43016736588544,131.35632576282202104.43016736588544
104994,53,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,...,68,109,172,75,488.0316041186948,167,25,5,69.54228578689846,488.031604118694869.54228578689846
104995,74,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,...,65,112,169,61,309.16444606680665,183,10,3,63.20478776719894,309.1644460668066563.20478776719894
104997,51,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,...,89,118,179,71,320.8304180033907,172,39,3,35.622420232475356,320.830418003390735.622420232475356

## Aggregate Data

In [9]:
#Summary Statistics

df.groupby(['average_heart_rate']).describe()

                   patient_age                 gender                      \
                         count unique top freq  count unique     top freq
average_heart_rate
100                        164     55  18    8    164      3    Male   63
101                        139     51  47    8    139      3  Female   48
102                        123     48  34    9    123      3    Male   42
103                         97     48  48    6     97      3    Male   39
104                         74     39  43    5     74      3    Male   29
...                        ...    ...  ..  ...    ...    ...     ...  ...
95                         466     65  38   21    466      3  Female  162
96                         391     64  18   19    391      3  Female  136
97                         271     60  18   17    271      3  Female   96
98                         245     58  43   14    245      3    Male   89
99                         194     54  18   12    194      3  Female   68

                   city_of_residence         ... number_of_tests       \
                               count unique  ...             top freq
average_heart_rate                           ...
100                              164    163  ...               3   41
101                              139    139  ...               4   45
102                              123    121  ...               5   27
103                               97     96  ...               4   25
104                               74     74  ...               4   19
...                              ...    ...  ...             ...  ...
95                               466    458  ...               4  117
96                               391    384  ...               4  113
97                               271    269  ...               4   74
98                               245    244  ...               4   73
99                               194    191  ...               4   53

                   prescription_cost_usd                                  \
                                   count unique                 top freq
average_heart_rate
100                                  164    164  121.81566974569479    1
101                                  139    139    49.7716961971473    1
102                                  123    123   62.67961218740668    1
103                                   97     97   77.59137456818915    1
104                                   74     74   143.1956904928686    1
...                                  ...    ...                 ...  ...
95                                   466    466   54.40329349191016    1
96                                   391    391   58.98709941331512    1
97                                   271    271   65.43337004241793    1
98                                   245    245  121.62694525094709    1
99                                   194    194   76.96592632951703    1

                   total_due_usd                                               \
                           count unique                                   top
average_heart_rate
100                          164    164  141.32470572798562121.81566974569479
101                          139    139     450.569871477036749.7716961971473
102                          123    123    119.428834511026662.67961218740668
103                           97     97    94.1337182052426977.59137456818915
104                           74     74   222.99410303626232143.1956904928686
...                          ...    ...                                   ...
95                           466    466    194.099536187086254.40329349191016
96                           391    391   282.0032115902526558.98709941331512
97                           271    271    36.6204726410602265.43337004241793
98                           245    245   28.15569324874495121.62694525094709
99                           194    194   387.0850435350886376.96592632951703


                   freq
average_heart_rate
100                   1
101                   1
102                   1
103                   1
104                   1
...                 ...
95                    1
96                    1
97                    1
98                    1
99                    1

[70 rows x 80 columns]

In [20]:
# Creating a pivot table to display the count of insured and uninsured individuals in each state

pivot_df = df.pivot_table(index='state_of_residence', columns='has_insurance', values='patient_age', aggfunc='count')
pivot_df

has_insurance        No  Yes
state_of_residence
Alabama             338  378
Alaska              339  357
Arizona             348  372
Arkansas            378  367
California          359  383
Colorado            378  349
Connecticut         389  367
Delaware            378  332
Florida             344  361
Georgia             361  358
Hawaii              332  335
Idaho               370  365
Illinois            348  352
Indiana             324  347
Iowa                372  401
Kansas              348  398
Kentucky            395  371
Louisiana           359  345
Maine               334  324
Maryland            338  366
Massachusetts       365  357
Michigan            331  360
Minnesota           400  374
Mississippi         376  367
Missouri            377  370
Montana             352  378
Nebraska            379  369
Nevada              329  366
New Hampshire       317  320
New Jersey          351  383
New Mexico          387  327
New York            385  363
North Carolina      373  328
North Dakota        339  387
Ohio                353  386
Oklahoma            329  354
Oregon              371  363
Pennsylvania        361  350
Rhode Island        363  364
South Carolina      323  367
South Dakota        354  328
Tennessee           358  380
Texas               367  349
Utah                324  352
Vermont             353  360
Virginia            363  330
Washington          362  336
West Virginia       345  353
Wisconsin           378  360
Wyoming             346  376

## Introduction to Alternative Libraries:
* Load dataset using Polars.
* Compare the load times and written observations

In [22]:
import polars as pl

In [23]:
df = pl.read_csv('https://raw.githubusercontent.com/Stephen-sanchez1/datasci_2_manipulation/main/datasets/healthcare_data_cleaning.csv')
df

shape: (105_000, 20)
┌───────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Patient   ┆ Gender ┆ City of    ┆ State of   ┆ … ┆ Last Visit ┆ Visit      ┆ Number of  ┆ Prescripti │
│ Age       ┆ ---    ┆ Residence  ┆ Residence  ┆   ┆ (days ago) ┆ Duration   ┆ Tests      ┆ on Cost    │
│ ---       ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ (mins)     ┆ ---        ┆ ($)        │
│ str       ┆        ┆ str        ┆ str        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│           ┆        ┆            ┆            ┆   ┆            ┆ str        ┆            ┆ str        │
╞═══════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 45        ┆ Other  ┆ West Brian ┆ Kentucky   ┆ … ┆ 193        ┆ 92         ┆ 5          ┆ 15.7175173 │
│           ┆        ┆            ┆            ┆   ┆            ┆            ┆            ┆ 5532889    │
│ 25        ┆ Female ┆ East Jocel ┆ Colorado   ┆ … ┆ 195        ┆ missing    ┆ 4          ┆ 80.7864728 │
│           ┆        ┆ ynfurt     ┆            ┆   ┆            ┆            ┆            ┆ 4463952    │
│ 51        ┆ Other  ┆ South Lind ┆ Ohio       ┆ … ┆ missing    ┆ 37         ┆ 2          ┆ 64.3921393 │
│           ┆        ┆ seyland    ┆            ┆   ┆            ┆            ┆            ┆ 009105     │
│ 18        ┆ Female ┆ Taylorfort ┆ Pennsylvan ┆ … ┆ 175        ┆ 108        ┆ 2          ┆ 8.87285921 │
│           ┆        ┆            ┆ ia         ┆   ┆            ┆            ┆            ┆ 5315316    │
│ …         ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 37        ┆ Male   ┆ Mckeetown  ┆ Utah       ┆ … ┆ 191        ┆ 47         ┆ 2          ┆ 113.867640 │
│           ┆        ┆            ┆            ┆   ┆            ┆            ┆            ┆ 25370326   │
│ 51        ┆ Female ┆ Lake Lisac ┆ Nebraska   ┆ … ┆ 172        ┆ 39         ┆ 3          ┆ 35.6224202 │
│           ┆        ┆ hester     ┆            ┆   ┆            ┆            ┆            ┆ 32475356   │
│ missing   ┆ Female ┆ Heidiborou ┆ missing    ┆ … ┆ 180        ┆ 79         ┆ missing    ┆ 124.408340 │
│           ┆        ┆ gh         ┆            ┆   ┆            ┆            ┆            ┆ 9893742    │
│ 45        ┆ Female ┆ South      ┆ Massachuse ┆ … ┆ 167        ┆ 81         ┆ missing    ┆ 87.9106014 │
│           ┆        ┆ Jeffrey    ┆ tts        ┆   ┆            ┆            ┆            ┆ 9353706    │
└───────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

## Comparing Load Times

* Pandas vs Polars

In [24]:
import time

In [27]:
start_time = time.time()
pd_df = pd.read_csv('https://raw.githubusercontent.com/Stephen-sanchez1/datasci_2_manipulation/main/datasets/healthcare_data_cleaning.csv')
pd_time = time.time() - start_time
f"Pandas Execution Time: {pd_time:.4f} seconds"

'Pandas Execution Time: 0.5816 seconds'

In [28]:
start_time = time.time()
pl_df = pl.read_csv('https://raw.githubusercontent.com/Stephen-sanchez1/datasci_2_manipulation/main/datasets/healthcare_data_cleaning.csv')
pl_time = time.time() - start_time
f"Polars Execution Time: {pl_time:.4f} seconds"

'Polars Execution Time: 0.2816 seconds'

## Observation

The observaiton from this comparison of load times is that Polars is much faster at loading datasets compared to pandas.